const LOG_IN = "LOG_IN";
const SIGN_UP = "SIGN_UP";
const SET_TOKEN = "SET_TOKEN";
const SET_TODOS = "SET_TODOS";
const ADD_TODOS = "ADD_TODOS";
const DELETE_TODOS = "DELETE_TODOS";
const EDIT_TODOS = "EDIT_TODOS";
const SET_USER = "SET_USER";
const COLORS = {
  MAIN_RED: "#DB4C3F",
  MAIN_BLACK: "#262C35",
  BG_GREY: "#EEEEEE",
  BG_BLUE: "#3025B9",
  URGENT: "#FF2831",
  HIGH: "#E38901",
  MEDIUM: "#3483E1",
  LOW: "#8C8C8C",
  CATEGORY: "#545454",
  TIME: "#6EBE6D",
  COMPLETED: "#08A835",
  BG_COMPLETED: "#DBEDDE",
  INPROGRESS: "#00ACD7",
  BORDER_GRAY: "#B8B8B8",
  LIGHT_GRAY: "#CDCDCD",
};
const CATEGORY_LIST = ["WORK", "PERSONAL"];
const PRIORITY_LIST = ["URGENT", "HIGH", "MEDIUM", "LOW"];
const TAB_STATUS = {
  IN_PROGRESS: "INPROGRESS",
  COMPLETED: "COMPLETED",
};

export {
  SET_TOKEN,
  COLORS,
  SET_TODOS,
  ADD_TODOS,
  DELETE_TODOS,
  EDIT_TODOS,
  LOG_IN,
  SIGN_UP,
  CATEGORY_LIST,
  PRIORITY_LIST,
  SET_USER,
  TAB_STATUS,
};
